from __future__ import annotations

from typing import Any

from preflight_validation import PREFLIGHT_CHECKS
from preflight_check_implementation import (
    validate_preflight_check_implementation_gate_result,
    validate_preflight_check_implementation_scaffold,
)


class PreflightEvidenceRecordError(ValueError):
    pass


VALID_EVIDENCE_REVIEW_DECISIONS = {
    "evidence_model_recorded",
    "needs_revision",
    "rejected",
}


REQUIRED_EVIDENCE_MODEL_FIELDS = [
    "preflight_evidence_model_id",
    "evidence_model_type",
    "evidence_model_status",
    "preflight_check_implementation_id",
    "checkpoint_id",
    "target_id",
    "scope_id",
    "tool",
    "adapter",
    "target_url",
    "target_mode",
    "local_only",
    "evidence_model_recorded",
    "evidence_records_defined",
    "evidence_records_generated",
    "all_required_evidence_records_defined",
    "all_required_evidence_records_generated",
    "all_required_checks_satisfied",
    "preflight_satisfied",
    "execution_authorized",
    "execution_authorization_satisfied",
    "runtime_enforcement_implemented",
    "ready_for_runtime_execution",
    "ready_for_customer_target",
    "ready_for_external_network",
    "preflight_evidence_records",
    "evidence_model_invariants",
    "evidence_model_blockers",
    "next_actions",
    "evidence_model_notes",
]


REQUIRED_RECORD_FIELDS = [
    "preflight_evidence_record_id",
    "check_name",
    "evidence_type",
    "evidence_record_status",
    "evidence_record_required",
    "evidence_record_generated",
    "check_implemented",
    "check_satisfied",
    "input_sources",
    "observed_inputs",
    "validation_result",
    "failure_mode",
    "fail_closed",
    "mismatch_detected",
    "stale_state_detected",
    "unsafe_state_detected",
    "ai_visible",
    "raw_artifact_capture_permitted",
    "sanitized_summary_required",
    "responsibility",
    "record_requirements",
]


REQUIRED_GATE_FIELDS = [
    "preflight_evidence_model_gate_type",
    "preflight_evidence_model_gate_status",
    "preflight_evidence_model_id",
    "preflight_check_implementation_id",
    "checkpoint_id",
    "target_id",
    "scope_id",
    "tool",
    "adapter",
    "target_url",
    "target_mode",
    "local_only",
    "evidence_review_decision",
    "evidence_review_satisfied",
    "evidence_records_defined",
    "evidence_records_generated",
    "all_required_evidence_records_defined",
    "all_required_evidence_records_generated",
    "all_required_checks_satisfied",
    "preflight_satisfied",
    "execution_authorized",
    "execution_authorization_satisfied",
    "runtime_enforcement_implemented",
    "ready_for_runtime_execution",
    "ready_for_customer_target",
    "ready_for_external_network",
    "scan_execution_allowed",
    "network_activity_allowed",
    "real_execution_permitted",
    "external_process_execution_allowed",
    "credential_injection_permitted",
    "raw_artifact_capture_permitted",
    "customer_target",
    "external_network_target",
    "blockers",
    "next_actions",
]


def _build_preflight_evidence_records(implementation: dict[str, Any]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []

    for item in implementation["check_implementations"]:
        check_name = item["check_name"]
        records.append(
            {
                "preflight_evidence_record_id": f"preflight-evidence-record-{check_name}",
                "check_name": check_name,
                "evidence_type": item["evidence_type"],
                "evidence_record_status": "record_model_defined_not_generated",
                "evidence_record_required": True,
                "evidence_record_generated": False,
                "check_implemented": False,
                "check_satisfied": False,
                "input_sources": list(item["input_sources"]),
                "observed_inputs": [],
                "validation_result": "not_evaluated",
                "failure_mode": "not_evaluated",
                "fail_closed": True,
                "mismatch_detected": False,
                "stale_state_detected": False,
                "unsafe_state_detected": False,
                "ai_visible": False,
                "raw_artifact_capture_permitted": False,
                "sanitized_summary_required": True,
                "responsibility": item["responsibility"],
                "record_requirements": [
                    "record must be generated by a future concrete preflight check implementation",
                    "record must remain non-AI-visible until sanitized if it contains raw inputs or raw outputs",
                    "record must preserve enough detail to reconstruct the preflight decision",
                    "record must fail closed when required inputs are missing",
                    "record must fail closed when runtime, target, scope, or authorization binding mismatches are detected",
                    "record must fail closed when stale state is detected",
                    "record must not authorize execution by itself",
                ],
            }
        )

    return records


def build_preflight_evidence_record_model(
    preflight_check_implementation: dict[str, Any],
    preflight_check_implementation_gate: dict[str, Any],
) -> dict[str, Any]:
    validate_preflight_check_implementation_scaffold(preflight_check_implementation)
    validate_preflight_check_implementation_gate_result(preflight_check_implementation_gate)

    if preflight_check_implementation["preflight_check_implementation_id"] != preflight_check_implementation_gate["preflight_check_implementation_id"]:
        raise PreflightEvidenceRecordError("preflight check implementation/gate ID mismatch")

    if preflight_check_implementation["checkpoint_id"] != preflight_check_implementation_gate["checkpoint_id"]:
        raise PreflightEvidenceRecordError("preflight check implementation/gate checkpoint_id mismatch")

    if preflight_check_implementation["target_id"] != preflight_check_implementation_gate["target_id"]:
        raise PreflightEvidenceRecordError("preflight check implementation/gate target_id mismatch")

    if preflight_check_implementation["scope_id"] != preflight_check_implementation_gate["scope_id"]:
        raise PreflightEvidenceRecordError("preflight check implementation/gate scope_id mismatch")

    records = _build_preflight_evidence_records(preflight_check_implementation)

    model = {
        "preflight_evidence_model_id": (
            f"preflight-evidence-model-{preflight_check_implementation['preflight_check_implementation_id']}"
        ),
        "evidence_model_type": "preflight_evidence_record_model",
        "evidence_model_status": "evidence_model_recorded_records_not_generated",
        "preflight_check_implementation_id": preflight_check_implementation["preflight_check_implementation_id"],
        "checkpoint_id": preflight_check_implementation["checkpoint_id"],
        "target_id": preflight_check_implementation["target_id"],
        "scope_id": preflight_check_implementation["scope_id"],
        "tool": preflight_check_implementation["tool"],
        "adapter": preflight_check_implementation["adapter"],
        "target_url": preflight_check_implementation["target_url"],
        "target_mode": preflight_check_implementation["target_mode"],
        "local_only": True,
        "evidence_model_recorded": True,
        "evidence_records_defined": True,
        "evidence_records_generated": False,
        "all_required_evidence_records_defined": True,
        "all_required_evidence_records_generated": False,
        "all_required_checks_satisfied": False,
        "preflight_satisfied": False,
        "execution_authorized": False,
        "execution_authorization_satisfied": False,
        "runtime_enforcement_implemented": False,
        "ready_for_runtime_execution": False,
        "ready_for_customer_target": False,
        "ready_for_external_network": False,
        "preflight_evidence_records": records,
        "evidence_model_invariants": {
            "local_only": True,
            "evidence_records_generated": False,
            "all_required_evidence_records_generated": False,
            "all_required_checks_satisfied": False,
            "preflight_satisfied": False,
            "execution_authorized": False,
            "execution_authorization_satisfied": False,
            "runtime_enforcement_implemented": False,
            "scan_execution_allowed": False,
            "network_activity_allowed": False,
            "real_execution_permitted": False,
            "external_process_execution_allowed": False,
            "credential_injection_permitted": False,
            "raw_artifact_capture_permitted": False,
            "customer_target": False,
            "external_network_target": False,
        },
        "evidence_model_blockers": [
            "preflight_evidence_records_not_generated",
            "concrete_preflight_checks_not_implemented",
            "all_required_checks_not_satisfied",
            "preflight_not_satisfied",
            "execution_authorization_not_satisfied",
            "runtime_enforcement_not_implemented",
            "sanitized_summaries_not_generated",
            "evidence_integrity_not_implemented",
            "preflight_reconstruction_not_verified",
        ],
        "next_actions": [
            "Define generated preflight evidence record examples for representative checks.",
            "Implement evidence record validation rules.",
            "Add negative tests for generated evidence that claims satisfied checks without required inputs.",
            "Add integrity and reconstruction expectations for preflight evidence records.",
            "Bind sanitized summaries before any evidence becomes AI-visible.",
        ],
        "evidence_model_notes": (
            "v0.3.1 defines the preflight evidence record model for all required checks. "
            "The records are defined but not generated. No check is satisfied, no preflight is satisfied, "
            "and execution remains blocked."
        ),
    }

    validate_preflight_evidence_record_model(model)
    return model


def validate_preflight_evidence_record_model(model: dict[str, Any]) -> None:
    missing = [field for field in REQUIRED_EVIDENCE_MODEL_FIELDS if field not in model]
    if missing:
        raise PreflightEvidenceRecordError(f"preflight evidence model missing fields: {missing}")

    if model.get("evidence_model_type") != "preflight_evidence_record_model":
        raise PreflightEvidenceRecordError("evidence_model_type must be preflight_evidence_record_model")

    if model.get("evidence_model_status") != "evidence_model_recorded_records_not_generated":
        raise PreflightEvidenceRecordError("evidence_model_status must be evidence_model_recorded_records_not_generated")

    if model.get("local_only") is not True:
        raise PreflightEvidenceRecordError("local_only must be true")

    required_true = [
        "evidence_model_recorded",
        "evidence_records_defined",
        "all_required_evidence_records_defined",
    ]
    for field in required_true:
        if model.get(field) is not True:
            raise PreflightEvidenceRecordError(f"{field} must be true")

    required_false = [
        "evidence_records_generated",
        "all_required_evidence_records_generated",
        "all_required_checks_satisfied",
        "preflight_satisfied",
        "execution_authorized",
        "execution_authorization_satisfied",
        "runtime_enforcement_implemented",
        "ready_for_runtime_execution",
        "ready_for_customer_target",
        "ready_for_external_network",
    ]
    for field in required_false:
        if model.get(field) is not False:
            raise PreflightEvidenceRecordError(f"{field} must be false")

    records = model.get("preflight_evidence_records", [])
    if not isinstance(records, list):
        raise PreflightEvidenceRecordError("preflight_evidence_records must be a list")

    record_names = {record.get("check_name") for record in records}
    missing_records = set(PREFLIGHT_CHECKS) - record_names
    if missing_records:
        raise PreflightEvidenceRecordError(f"preflight evidence records missing checks: {sorted(missing_records)}")

    for record in records:
        validate_preflight_evidence_record(record)

    invariants = model.get("evidence_model_invariants", {})
    if invariants.get("local_only") is not True:
        raise PreflightEvidenceRecordError("evidence model invariant local_only must be true")

    invariant_false = [
        "evidence_records_generated",
        "all_required_evidence_records_generated",
        "all_required_checks_satisfied",
        "preflight_satisfied",
        "execution_authorized",
        "execution_authorization_satisfied",
        "runtime_enforcement_implemented",
        "scan_execution_allowed",
        "network_activity_allowed",
        "real_execution_permitted",
        "external_process_execution_allowed",
        "credential_injection_permitted",
        "raw_artifact_capture_permitted",
        "customer_target",
        "external_network_target",
    ]
    for field in invariant_false:
        if invariants.get(field) is not False:
            raise PreflightEvidenceRecordError(f"evidence model invariant must be false: {field}")

    required_blockers = {
        "preflight_evidence_records_not_generated",
        "concrete_preflight_checks_not_implemented",
        "all_required_checks_not_satisfied",
        "preflight_not_satisfied",
        "execution_authorization_not_satisfied",
        "runtime_enforcement_not_implemented",
        "sanitized_summaries_not_generated",
        "evidence_integrity_not_implemented",
        "preflight_reconstruction_not_verified",
    }
    missing_blockers = required_blockers - set(model.get("evidence_model_blockers", []))
    if missing_blockers:
        raise PreflightEvidenceRecordError(f"preflight evidence model missing blockers: {sorted(missing_blockers)}")


def validate_preflight_evidence_record(record: dict[str, Any]) -> None:
    missing = [field for field in REQUIRED_RECORD_FIELDS if field not in record]
    if missing:
        raise PreflightEvidenceRecordError(f"preflight evidence record missing fields: {missing}")

    if record.get("check_name") not in PREFLIGHT_CHECKS:
        raise PreflightEvidenceRecordError(f"unknown check_name: {record.get('check_name')}")

    if record.get("evidence_record_status") != "record_model_defined_not_generated":
        raise PreflightEvidenceRecordError("evidence_record_status must be record_model_defined_not_generated")

    required_true = [
        "evidence_record_required",
        "fail_closed",
        "sanitized_summary_required",
    ]
    for field in required_true:
        if record.get(field) is not True:
            raise PreflightEvidenceRecordError(f"{field} must be true")

    required_false = [
        "evidence_record_generated",
        "check_implemented",
        "check_satisfied",
        "mismatch_detected",
        "stale_state_detected",
        "unsafe_state_detected",
        "ai_visible",
        "raw_artifact_capture_permitted",
    ]
    for field in required_false:
        if record.get(field) is not False:
            raise PreflightEvidenceRecordError(f"{field} must be false")

    if record.get("validation_result") != "not_evaluated":
        raise PreflightEvidenceRecordError("validation_result must be not_evaluated")

    if record.get("failure_mode") != "not_evaluated":
        raise PreflightEvidenceRecordError("failure_mode must be not_evaluated")

    if record.get("observed_inputs") != []:
        raise PreflightEvidenceRecordError("observed_inputs must be empty in the model scaffold")

    if not record.get("input_sources"):
        raise PreflightEvidenceRecordError("input_sources must not be empty")

    if not record.get("evidence_type"):
        raise PreflightEvidenceRecordError("evidence_type must not be empty")


def evaluate_preflight_evidence_record_model_gate(
    model: dict[str, Any],
    *,
    evidence_review_decision: str = "evidence_model_recorded",
) -> dict[str, Any]:
    validate_preflight_evidence_record_model(model)

    if evidence_review_decision not in VALID_EVIDENCE_REVIEW_DECISIONS:
        raise PreflightEvidenceRecordError(f"unsupported evidence_review_decision: {evidence_review_decision}")

    if evidence_review_decision == "evidence_model_recorded":
        gate_status = "evidence_model_recorded_execution_blocked"
        blockers = list(model["evidence_model_blockers"])
    elif evidence_review_decision == "needs_revision":
        gate_status = "needs_revision"
        blockers = list(model["evidence_model_blockers"])
    else:
        gate_status = "rejected"
        blockers = ["preflight_evidence_record_model_rejected"]

    invariants = model["evidence_model_invariants"]

    gate = {
        "preflight_evidence_model_gate_type": "preflight_evidence_record_model_gate",
        "preflight_evidence_model_gate_status": gate_status,
        "preflight_evidence_model_id": model["preflight_evidence_model_id"],
        "preflight_check_implementation_id": model["preflight_check_implementation_id"],
        "checkpoint_id": model["checkpoint_id"],
        "target_id": model["target_id"],
        "scope_id": model["scope_id"],
        "tool": model["tool"],
        "adapter": model["adapter"],
        "target_url": model["target_url"],
        "target_mode": model["target_mode"],
        "local_only": True,
        "evidence_review_decision": evidence_review_decision,
        "evidence_review_satisfied": False,
        "evidence_records_defined": True,
        "evidence_records_generated": False,
        "all_required_evidence_records_defined": True,
        "all_required_evidence_records_generated": False,
        "all_required_checks_satisfied": False,
        "preflight_satisfied": False,
        "execution_authorized": False,
        "execution_authorization_satisfied": False,
        "runtime_enforcement_implemented": False,
        "ready_for_runtime_execution": False,
        "ready_for_customer_target": False,
        "ready_for_external_network": False,
        "scan_execution_allowed": invariants["scan_execution_allowed"],
        "network_activity_allowed": invariants["network_activity_allowed"],
        "real_execution_permitted": invariants["real_execution_permitted"],
        "external_process_execution_allowed": invariants["external_process_execution_allowed"],
        "credential_injection_permitted": invariants["credential_injection_permitted"],
        "raw_artifact_capture_permitted": invariants["raw_artifact_capture_permitted"],
        "customer_target": invariants["customer_target"],
        "external_network_target": invariants["external_network_target"],
        "blockers": blockers,
        "next_actions": [
            {
                "blocker": "preflight_evidence_records_not_generated",
                "next_action": "Add generated evidence record examples for representative preflight checks.",
            },
            {
                "blocker": "evidence_integrity_not_implemented",
                "next_action": "Define evidence integrity fields and validation rules.",
            },
            {
                "blocker": "preflight_reconstruction_not_verified",
                "next_action": "Define reconstruction tests from preflight evidence records back to authorization decision.",
            },
            {
                "blocker": "sanitized_summaries_not_generated",
                "next_action": "Define sanitized summaries before any preflight evidence can become AI-visible.",
            },
        ],
    }

    validate_preflight_evidence_record_model_gate_result(gate)
    return gate


def validate_preflight_evidence_record_model_gate_result(gate: dict[str, Any]) -> None:
    missing = [field for field in REQUIRED_GATE_FIELDS if field not in gate]
    if missing:
        raise PreflightEvidenceRecordError(f"preflight evidence model gate missing fields: {missing}")

    if gate.get("preflight_evidence_model_gate_type") != "preflight_evidence_record_model_gate":
        raise PreflightEvidenceRecordError("preflight_evidence_model_gate_type mismatch")

    if gate.get("evidence_review_decision") not in VALID_EVIDENCE_REVIEW_DECISIONS:
        raise PreflightEvidenceRecordError("unsupported evidence_review_decision")

    if gate.get("local_only") is not True:
        raise PreflightEvidenceRecordError("local_only must be true")

    required_true = [
        "evidence_records_defined",
        "all_required_evidence_records_defined",
    ]
    for field in required_true:
        if gate.get(field) is not True:
            raise PreflightEvidenceRecordError(f"{field} must be true")

    required_false = [
        "evidence_review_satisfied",
        "evidence_records_generated",
        "all_required_evidence_records_generated",
        "all_required_checks_satisfied",
        "preflight_satisfied",
        "execution_authorized",
        "execution_authorization_satisfied",
        "runtime_enforcement_implemented",
        "ready_for_runtime_execution",
        "ready_for_customer_target",
        "ready_for_external_network",
        "scan_execution_allowed",
        "network_activity_allowed",
        "real_execution_permitted",
        "external_process_execution_allowed",
        "credential_injection_permitted",
        "raw_artifact_capture_permitted",
        "customer_target",
        "external_network_target",
    ]
    for field in required_false:
        if gate.get(field) is not False:
            raise PreflightEvidenceRecordError(f"{field} must be false")

    if not gate.get("blockers"):
        raise PreflightEvidenceRecordError("preflight evidence model gate must include blockers")
