from __future__ import annotations

import subprocess
import sys


def run(cmd: list[str]) -> None:
    print("+", " ".join(cmd))
    subprocess.run(cmd, check=True)


def main() -> int:
    run([sys.executable, "-m", "compileall", "-q", "prototypes", "tools"])
    run([sys.executable, "tools/validate_mvp_schemas.py"])
    run([sys.executable, "tools/validate_mvp_examples.py"])
    run([sys.executable, "tools/test_scope_registry.py"])
    run([sys.executable, "tools/run_tool_gateway_example.py", "all"])
    run([sys.executable, "tools/validate_generated_outputs.py"])
    run([sys.executable, "tools/test_tool_gateway_runner.py"])
    run([sys.executable, "tools/test_tool_gateway_adapters.py"])
    run([sys.executable, "tools/test_controlled_executor_policy.py"])
    run([sys.executable, "tools/test_real_execution_readiness_gate.py"])
    run([sys.executable, "tools/test_operator_readiness_review.py"])
    run([sys.executable, "tools/test_human_approval_gate.py"])
    run([sys.executable, "tools/test_evidence_chain_linkage.py"])
    run([sys.executable, "tools/test_evidence_reconstruction_report.py"])
    run([sys.executable, "tools/test_sanitizer_redaction_policy.py"])
    run([sys.executable, "tools/test_finding_candidate_model.py"])
    run([sys.executable, "tools/test_finding_review_gate.py"])
    run([sys.executable, "tools/test_report_finding_promotion_gate.py"])
    run([sys.executable, "tools/test_report_review_gate.py"])
    run([sys.executable, "tools/test_report_packet_review_gate.py"])
    run([sys.executable, "tools/test_delivery_authorization_gate.py"])
    run([sys.executable, "tools/test_lifecycle_integration_checkpoint.py"])
    run([sys.executable, "tools/test_runtime_readiness_gate.py"])
    run([sys.executable, "tools/test_local_target_lab_profile.py"])
    run([sys.executable, "tools/test_runtime_destination_binding.py"])
    run([sys.executable, "tools/test_bounded_execution_transition_candidate.py"])
    run([sys.executable, "tools/test_local_execution_plan_review.py"])
    run([sys.executable, "tools/test_runtime_safety_policy.py"])
    run([sys.executable, "tools/test_runtime_enforcement_design.py"])
    run([sys.executable, "tools/test_execution_authorization_gate.py"])
    run([sys.executable, "tools/test_preflight_validation.py"])
    run([sys.executable, "tools/test_runtime_transition_checkpoint.py"])
    run([sys.executable, "tools/test_preflight_check_implementation.py"])
    run([sys.executable, "tools/test_preflight_evidence_record_model.py"])
    run([sys.executable, "tools/test_preflight_evidence_examples.py"])
    run([sys.executable, "tools/test_preflight_evidence_validation_rules.py"])
    run([sys.executable, "tools/test_preflight_evidence_negative_examples.py"])
    run([sys.executable, "tools/test_licensing_and_commercial_use_boundary.py"])
    run([sys.executable, "tools/test_public_repository_readiness_checkpoint.py"])
    run([sys.executable, "tools/test_publication_hygiene_private_artifact_exclusion.py"])
    run([sys.executable, "tools/test_public_security_policy_vulnerability_disclosure.py"])
    run([sys.executable, "tools/test_first_publication_repository_settings_checklist.py"])
    run([sys.executable, "tools/test_v040_publication_preparation_release.py"])
    run([sys.executable, "tools/test_github_actions_ci_scaffold.py"])
    run([sys.executable, "tools/test_readme_public_english_wording.py"])
    run([sys.executable, "tools/test_public_facing_repository_metadata_announcement_pack.py"])
    run([sys.executable, "tools/test_public_repository_launch_checkpoint.py"])
    run([sys.executable, "tools/test_public_release_notes_launch_announcement_package.py"])
    run([sys.executable, "tools/test_github_release_publication_checkpoint.py"])
    run([sys.executable, "tools/test_commercial_adoption_preparation_checkpoint.py"])
    run([sys.executable, "tools/test_readme_public_baseline_commercial_entrypoint_cleanup.py"])
    run([sys.executable, "tools/test_readme_compatibility_phrase_registry.py"])
    run([sys.executable, "tools/test_licensing_trademark_authorship_protection.py"])
    run([sys.executable, "tools/test_dependency_repository_governance_readiness.py"])
    run([sys.executable, "tools/test_github_repository_ruleset_branch_protection_planning.py"])
    run([sys.executable, "tools/test_release_governance_maintainer_operations_checklist.py"])
    run([sys.executable, "tools/test_public_trust_reviewer_navigation.py"])
    run([sys.executable, "tools/test_public_front_page_landing_polish.py"])
    run([sys.executable, "tools/test_public_evidence_capability_boundary_summary.py"])
    run([sys.executable, "tools/test_public_faq_reviewer_objections.py"])
    run([sys.executable, "tools/test_v060_implementation_evaluation_work_ordering.py"])
    run([sys.executable, "tools/test_v061_capability_inventory_maturity_map.py"])
    run([sys.executable, "tools/test_v062_evaluation_criteria_acceptance_model.py"])
    run([sys.executable, "tools/test_v063_safety_boundary_non_goal_review.py"])
    run([sys.executable, "tools/test_v064_local_assessment_lab_decision_record.py"])
    run([sys.executable, "tools/test_v065_documentation_only_local_lab_profile_action_taxonomy.py"])
    run([sys.executable, "tools/test_v066_ai_request_decision_boundary_tool_selection_criteria.py"])
    run([sys.executable, "tools/test_v067_observation_normalization_diagnostic_fidelity_risk_review.py"])
    run([sys.executable, "tools/test_v068_demo_scenario_reviewer_walkthrough_planning.py"])
    run([sys.executable, "tools/test_v069_evidence_reconstruction_sample_report_demonstration_planning.py"])
    run([sys.executable, "tools/test_v0610_safe_docker_lab_roadmap_local_target_candidate_planning.py"])
    run([sys.executable, "tools/test_v0611_local_lab_candidate_profile_preflight_evidence_planning.py"])
    run([sys.executable, "tools/test_v0612_non_running_docker_compose_design_review_planning.py"])
    run([sys.executable, "tools/test_v0613_static_compose_design_sketch_network_boundary_review.py"])
    run([sys.executable, "tools/test_v0614_static_lab_scenario_fixture_planning.py"])
    run([sys.executable, "tools/test_v0615_static_fixture_schema_validator_planning.py"])
    run([sys.executable, "tools/test_v0616_static_fixture_schema_draft_negative_test_planning.py"])
    run([sys.executable, "tools/test_v0617_static_fixture_validator_scaffold_planning.py"])
    run([sys.executable, "tools/test_v0618_static_fixture_validator_minimal_scaffold_design.py"])
    run([sys.executable, "tools/test_v0619_static_fixture_validator_implementation_readiness_review.py"])
    run([sys.executable, "tools/test_v0620_static_fixture_validator_read_only_implementation_scaffold.py"])
    run([sys.executable, "tools/test_v0621_static_fixture_validator_required_node_check_planning.py"])
    run([sys.executable, "tools/test_v0622_aaef_applied_evidence_work_intake_current_state_review.py"])
    run([sys.executable, "tools/test_v0623_aaef_applied_evidence_package_design.py"])
    run([sys.executable, "tools/test_v0624_applied_evidence_scenario_set_planning.py"])
    run([sys.executable, "tools/test_v0625_static_applied_evidence_fixture_planning.py"])
    run([sys.executable, "tools/test_v0626_reviewer_walkthrough_five_questions_mapping.py"])
    run([sys.executable, "tools/test_v0627_applied_evidence_structural_validator_planning.py"])
    run([sys.executable, "tools/test_v0628_static_mock_applied_evidence_generation_readiness_review.py"])
    run([sys.executable, "tools/test_v0629_static_mock_applied_evidence_package_private_generation_candidate.py"])
    run([sys.executable, "tools/test_v0630_static_mock_applied_evidence_review_promotion_gate_planning.py"])
    run([sys.executable, "tools/test_v0631_static_mock_applied_evidence_private_review_record.py"])
    run([sys.executable, "tools/test_v0632_static_mock_applied_evidence_public_sample_promotion_decision_record.py"])
    run([sys.executable, "tools/test_v0633_sanitized_public_sample_planning.py"])
    run([sys.executable, "tools/test_v0634_sanitized_public_sample_generation_readiness_review.py"])
    run([sys.executable, "tools/test_v0635_sanitized_public_sample_generation_candidate.py"])
    run([sys.executable, "tools/test_v0636_sanitized_public_sample_publication_review_record.py"])
    run([sys.executable, "tools/test_v0637_sanitized_public_sample_close_readiness_review.py"])
    run([sys.executable, "tools/test_v0638_public_example_structural_validation_planning.py"])
    run([sys.executable, "tools/test_v0639_public_example_structural_validator_implementation_readiness_review.py"])
    run([sys.executable, "tools/test_v0640_public_example_structural_validator_implementation_candidate.py"])
    run([sys.executable, "tools/test_v0641_public_example_structural_validator_review_close_readiness.py"])
    run([sys.executable, "tools/test_v0642_aaef_applied_implementation_handback_summary.py"])
    run([sys.executable, "tools/test_v0643_applied_implementation_handback_review_next_direction.py"])
    run([sys.executable, "tools/test_v0644_public_validator_negative_fixture_planning.py"])

    run([sys.executable, "tools/test_v0645_public_validator_negative_fixture_implementation_readiness_review.py"])


    run([sys.executable, "tools/test_v0646_public_validator_negative_fixture_implementation_candidate.py"])
    run([sys.executable, "tools/test_v0647_public_validator_negative_fixture_coverage_review_close_readiness.py"])
    run([sys.executable, "tools/test_v0648_public_validator_negative_fixture_coverage_hardening_planning.py"])
    print("All local checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
